#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have symbolic links called "trees" and "friends", pointing to your
# trees and friend trees, resp.

lumi=35.9
#mca=susy-1lep/mca/test.txt

mca=susy-1lep/mca/mca-Summer16_Moriond17.txt
cuts=susy-1lep/1l_basicCutsFullCutFlow.txt
trees=/eos/cms/store/user/sdogra/monotop/background
friends=/eos/cms/store/user/sdogra/monotop/friendtrees/evVarFriend_{cname}.root

# QCD estimation, define QCD as signal
#python mcTrees.py \
python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    susy-1lep/plots/base_plots1.txt \
    -P "${trees}" \
    -F sf/t "${friends}" \
    -l "${lumi}" \
    -j $(nproc) \
    --tree treeProducerSusySingleLepton \
    -G \
    -f \
    --showRatio \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs \
    --scaleBkgToData TTsemiLep \
    --scaleBkgToData TTdiLep \
    --scaleBkgToData TTV \
    --scaleBkgToData SingleT \
    --scaleBkgToData WJets \
    --scaleBkgToData DY \
    --scaleBkgToData VV \
    --scaleBkgToData QCD \
    --showSF

## Fit QCD estimation to data in anti-selected region; this is only useful for
## plotting; define QCD as background
#python mcPlots.py \
#    "${mca}" \
#    susy-1lep/mca/mycuts.txt \
#    susy-1lep/mca/myplots.txt \
#    -P "${trees}" \
#    -F sf/t "${friends}" \
#    -l "${lumi}" \
#    -j $(nproc) \
#    --tree treeProducerSusySingleLepton \
#    -G \
#    -f \
#    --noStackSig \
#    --showIndivSigs \
#    --showRatio \
#    --maxRatioRange 0.0 2.0 \
#    --fixRatioRange \
#    --noErrorBandOnRatio \
#    --scaleBkgToData QCD \
#    --showSF

