// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/work/s/sdogra/monotop/CMSSW_8_0_25/src/CMGTools/SUSYAnalysis/macros/./../python/tools/WPolarizationVariation.C";

#endif
