xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/DYJetsToLL_M50_HT1200to2500/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/DYJetsToLL_M50_HT2500toInf/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/DYJetsToLL_M50_HT400to600/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/DYJetsToLL_M50_HT600to800/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/DYJetsToLL_M50_HT800to1200/ . 
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT1000to1500/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT1500to2000/ . 
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT2000toInf/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT300to500/ . 
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT500to700/ . 
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/QCD_HT700to1000/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TBar_tWch/ . 
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TBar_tch_powheg/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_DiLepton/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_LO_HT1200to2500/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_LO_HT2500toInf/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_LO_HT600to800/ .
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_LO_HT800to1200/ /tmp/sdogra/TTJets_LO_HT800to1200/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_SingleLeptonFromT/  /tmp/sdogra/TTJets_SingleLeptonFromT/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTJets_SingleLeptonFromTbar/ /tmp/sdogra/TTJets_SingleLeptonFromTbar.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTWToLNu/ /tmp/sdogra/TTWToLNu/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTWToQQ/ /tmp/sdogra/TTWToQQ/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTZToLLNuNu/  /tmp/sdogra/TTZToLLNuNu/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TTZToQQ/  /tmp/sdogra/TTZToQQ/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/TToLeptons_sch/  /tmp/sdogra/TToLeptons_sch/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/T_tWch/  /tmp/sdogra/T_tWch/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/T_tch_powheg/  /tmp/sdogra/T_tch_powheg/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WJetsToLNu_HT1200to2500/  /tmp/sdogra/WJetsToLNu_HT1200to2500/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WJetsToLNu_HT2500toInf/  /tmp/sdogra/WJetsToLNu_HT2500toInf/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WJetsToLNu_HT400to600/  /tmp/sdogra/WJetsToLNu_HT400to600/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WJetsToLNu_HT600to800/  /tmp/sdogra/WJetsToLNu_HT600to800/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WJetsToLNu_HT800to1200/  /tmp/sdogra/WJetsToLNu_HT800to1200/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WWTo2L2Nu/  /tmp/sdogra/WWTo2L2Nu/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WWToLNuQQ/  /tmp/sdogra/WWToLNuQQ/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WZTo1L1Nu2Q/  /tmp/sdogra/WZTo1L1Nu2Q/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WZTo1L3Nu/  /tmp/sdogra/WZTo1L3Nu/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/WZTo2L2Q/  /tmp/sdogra/WZTo2L2Q/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/ZZTo2L2Nu/  /tmp/sdogra/ZZTo2L2Nu/.
xrdcp -r  /eos/cms/store/user/bschneid/dark_matter/bg_v01/ZZTo2L2Q/  /tmp/sdogra/ZZTo2L2Q/.
