eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT100to200/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT1200to2500/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT200to400/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT2500toInf/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT400to600/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT600to800/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT70to100/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/DYJetsToLL_M50_HT800to1200/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT1000to1500/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT100to200/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT1500to2000/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT2000toInf/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT200to300/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT300to500/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT500to700/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/QCD_HT700to1000/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TBar_tWch_ext1/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TBar_tch_powheg/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TTJets_DiLepton/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TTJets_SingleLeptonFromT/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TTJets_SingleLeptonFromTbar/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TTWToLNu_ext/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TTZToLLNuNu/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/TToLeptons_sch/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/T_tWch_ext1/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/T_tch_powheg/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT100to200_ext/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT1200to2500/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT200to400_ext/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT2500toInf/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT400to600/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT600to800/treeProducerSusySingleLepton
eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WJetsToLNu_HT800to1200_ext/treeProducerSusySingleLepton
#eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WWTo2L2Nu/treeProducerSusySingleLepton
#eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WWToLNuQQ/treeProducerSusySingleLepton
#eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/WZTo1L3Nu/treeProducerSusySingleLepton
#eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/ZZTo2L2Nu/treeProducerSusySingleLepton
#eos ls -ltrh  /eos/cms/store/user/bschneid/dark_matter/bg_v02/ZZTo2L2Q/treeProducerSusySingleLepton
