#!/usr/bin/env bash

if [ -z "${1}" ]; then
    echo Please specify outputfolder as positional argument.
    exit
fi

lumi=35.9
outputdir="${1}"

# Signal
./makeBinYields.py \
    --mca mca/mca-Spring16_Signal_forMoriond17.txt \
    --signal \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/scan

# Background
./makeBinYields.py \
    --mca mca/mca-Summer16_Moriond17.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid

# Background with dilepton nJet correction
./makeBinYields.py \
    --mca mca/mca-Summer16_Moriond17_dilep-corr.txt \
    --grid \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/grid-dilep

# Systematic: dilepton constant
./makeBinYields.py \
    --mca ../systs/DLConst/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLConst

# Systematic: dilepton slope
./makeBinYields.py \
    --mca ../systs/DLSlope/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_DLSlope

# Systematic: JEC
./makeBinYields.py \
    --mca ../systs/JEC/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_JEC

## Systematic: PDF
#./makeBinYields.py \
#    --mca ../systs/PDFUnc-RMS/mca-Summer16_Moriond17.txt \
#    --grid \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/syst_PDFUnc-RMS

## Systematic: scale match
#./makeBinYields.py \
#    --mca ../systs/ScaleMatchVar/mca-Summer16_Moriond17.txt \
#    --grid \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/syst_ScaleMatchVar

# Systematic: W polarization
./makeBinYields.py \
    --mca ../systs/Wpol/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wpol

# Systematic: W cross section
./makeBinYields.py \
    --mca ../systs/Wxsec/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_Wxsec

# Systematic: b-tagging heavy flavour
./makeBinYields.py \
    --mca ../systs/btagHF/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagHF

# Systematic: b-tagging
./makeBinYields.py \
    --mca ../systs/btagLF/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_btagLF

# Systematic: lepton SF
./makeBinYields.py \
    --mca ../systs/lepSF/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_lepSF

# Systematic: pileup
./makeBinYields.py \
    --mca ../systs/PU/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_PU

# Systematic: TTV cross section
./makeBinYields.py \
    --mca ../systs/TTVxsec/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTVxsec

# Systematic: TT cross section
./makeBinYields.py \
    --mca ../systs/TTxsec/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_TTxsec

# Systematic: nISR reweighting
./makeBinYields.py \
    --mca ../systs/nISR/mca-Summer16_Moriond17.txt \
    --grid \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/syst_nISR

# Signal systematic: Gluino ISR
./makeBinYields.py \
    --mca ../systs/signal/ISR/mca-Spring16_Signal_forMoriond17.txt \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_ISR

# Signal systematic: JEC
./makeBinYields.py \
    --mca ../systs/signal/JEC/mca-Spring16_Signal_forMoriond17.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_JEC

# Signal systematic: btag heavy flavour
./makeBinYields.py \
    --mca ../systs/signal/btagHF/mca-Spring16_Signal_forMoriond17.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagHF

# Signal systematic: btag light flavour
./makeBinYields.py \
    --mca ../systs/signal/btagLF/mca-Spring16_Signal_forMoriond17.txt  \
    --signal \
    --systs True \
    -v 2 \
    -l "${lumi}" \
    -b \
    --od "${outputdir}"/signal_btagLF

# does not work out of the box, because the new signal samples are not in 
# the same place as the old ones (yet) and the paths are hardcoded in 
# makeBinYields
## Signal systematic: scale variation
#./makeBinYields.py \
#    --mca ../systs/signal/scale/mca-Spring16_Signal_forMoriond17.txt  \
#    --signal \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/signal_scale

## Signal systematic: pileup
#./makeBinYields.py \
#    --mca ../systs/signal/PU/mca-Spring16_Signal_forMoriond17.txt  \
#    --signal \
#    --systs True \
#    -v 2 \
#    -l "${lumi}" \
#    -b \
#    --od "${outputdir}"/signal_PU

